export const KEY_BINDINGS = {
  ROLL: Phaser.Input.Keyboard.KeyCodes.ALT,
  INTERACT: Phaser.Input.Keyboard.KeyCodes.SPACE,
  ATTACK: Phaser.Input.Keyboard.KeyCodes.CTRL,
  NUM_0: Phaser.Input.Keyboard.KeyCodes.ZERO,
  NUM_1: Phaser.Input.Keyboard.KeyCodes.ONE,
  NUM_2: Phaser.Input.Keyboard.KeyCodes.TWO,
  NUM_3: Phaser.Input.Keyboard.KeyCodes.THREE,
  NUM_4: Phaser.Input.Keyboard.KeyCodes.FOUR,
  NUM_5: Phaser.Input.Keyboard.KeyCodes.FIVE,
  NUM_6: Phaser.Input.Keyboard.KeyCodes.SIX,
  NUM_7: Phaser.Input.Keyboard.KeyCodes.SEVEN,
  NUM_8: Phaser.Input.Keyboard.KeyCodes.EIGHT,
  NUM_9: Phaser.Input.Keyboard.KeyCodes.NINE,
  NUMPAD_0: Phaser.Input.Keyboard.KeyCodes.NUMPAD_ZERO,
  NUMPAD_1: Phaser.Input.Keyboard.KeyCodes.NUMPAD_ONE,
  NUMPAD_2: Phaser.Input.Keyboard.KeyCodes.NUMPAD_TWO,
  NUMPAD_3: Phaser.Input.Keyboard.KeyCodes.NUMPAD_THREE,
  NUMPAD_4: Phaser.Input.Keyboard.KeyCodes.NUMPAD_FOUR,
  NUMPAD_5: Phaser.Input.Keyboard.KeyCodes.NUMPAD_FIVE,
  NUMPAD_6: Phaser.Input.Keyboard.KeyCodes.NUMPAD_SIX,
  NUMPAD_7: Phaser.Input.Keyboard.KeyCodes.NUMPAD_SEVEN,
  NUMPAD_8: Phaser.Input.Keyboard.KeyCodes.NUMPAD_EIGHT,
  NUMPAD_9: Phaser.Input.Keyboard.KeyCodes.NUMPAD_NINE,
};
